### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by trey33088** [eddiez9/sans-ondemand-download#1]
Hi, I'm receiving a key error whenever I'm attempting to run this. Do you have any ideas why? I am new to python, and currently ironically trying to download the SEC 573 for python .  Any help would be appreciated. I've included a snapshot, as well as my uberRequest file (as a Text file)
![Key Error](https://user-images.githubusercontent.com/48400351/54081101-d244da00-42cc-11e9-91c7-5bb935ae08f6.PNG)

[uberRequest.txt](https://github.com/eddiez9/sans-ondemand-download/files/2949089/uberRequest.txt)

**Comment by eddiez9** [comment]
Hi there,

It appears you're downloading the response content incorrectly.

Search for "223212" in that file you attached. The contents of that specific response is the one you need and nothing else. A way to download it properly in Chrome is to:
1. Press F12
2. Click the Network tab
3. Browse to the page where you can actually watch the videos.
4. Right click on the uber request and open in new tab
5. Right click content on screen and save as somewhere on your computer

Or if you can't get that working attach the same capture again and I can parse out/unescape the correct content and get it back to you before the cookies expire.

**Comment by trey33088** [comment]
That fixed it. 720p takes up a very large amount of space; How would I go about downloading the 480p instead of 720p?

**Comment by eddiez9** [comment]
The script is hard-coded to download in 720p, I'll add a command-line argument to switch between 720p and 480p this weekend.

Although it might be beneficial for your learning of python and json to try to make the change yourself given the course you're taking. 😉

**Comment by trey33088** [comment]
Worked through the download and json code, and I have a feeling it has to do with cookies (I noticed you the video, plus the cookies, and everything towards the end the video request in the json is a what appears to be a hashed cookie. Still learning.

**Comment by eddiez9** [comment]
You're on the right path. Consider placing some print statements to figure out what the request at # Get video list gives you. Maybe with a 'print response.content'.

But if you just want to get the videos for now in SD:
I've updated the script with a command line variable (-q) to switch between HD and SD. If you run a git pull to get the latest version of the script it should allow you do go ./download.py -q SD uberRequest.json
