### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by saladolf** [eddiez9/sans-ondemand-download#4]
Hi
The script starts downloading the contents correctly for the first module, then when it moves to the second module, I am getting an error:
================
Downloading Video: Security 401 SANS Security Essentials bootcamp style Introduction to Lab Exercises
Traceback (most recent call last):
  File "download.py", line 107, in <module>
    download_if_not_exist(baseUrl+video['video'][video_quality]['URI'], cookies, video_path)
  File "download.py", line 32, in download_if_not_exist
    with open(tmp_file_path, 'wb') as f:
IOError: [Errno 2] No such file or directory: u'SEC401 Security Essentials Bootcamp Style E02026125/1. Getting Started with SANS OnDemand/2. Introduction to Lab Exercises/1. Security 401 SANS Security Essentials bootcamp style Introduction to Lab Exercises.mp4.part'
================

Am I doing something wrong? should I repeat the process you provided (getting the JSON) for every module one by one?

**Comment by eddiez9** [comment]
Hi @saladolf,

You shouldn't need to repeat the process for each module.

I assume you're on Windows? Windows path lengths are limited to 260 characters. Given the first module downloaded correctly there should be no reason why the rest won't work. 

Can you try running the script with the '-t' flag and let me know if that works?

**Comment by eddiez9** [comment]
Haven't heard back so i'm assuming using -t fixed your issue.
