### ISSUE TITLE
no uberRequest shows up

### ISSUE THREAD

**Issue by 3ra5mu5** [eddiez9/sans-ondemand-download#6]
Using Chrome Version 77.0.3865.120 (Official Build) (64-bit), there does not appear to be any uberRequest.  Is there another file to look for?  Is it a change by Chrome or SANS?  Any way around it?

Thanks.

**Comment by eddiez9** [comment]
Just checked now, still there.

The request occurs when you browse to https://olt-players.sans.org/

You can add a filter called uber to help you locate the request.

![image](https://user-images.githubusercontent.com/4555207/68015760-0307d280-fce7-11e9-8ebb-24ee29c59f91.png)

**Comment by 3ra5mu5** [comment]
I found it.  Had to click through to the next page and then reload that page for it to show up.  Thanks.

**Comment by ahiguero** [comment]
eve with the filter i am unable to find that uberRequest.php entry
