### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by 3ra5mu5** [eddiez9/sans-ondemand-download#7]
Running into a problem with line 134.  Here's my output.  

Downloading Video: Out of Class Exercise Hard Drive Acquisition with Write Blocker USB  Documents and Cheatsheets
Traceback (most recent call last):
  File "K:\sans-ondemand-download-master\download.py", line 134, in <module>
    download_if_not_exist(baseUrl + video['video'][video_quality]['URI'], cookies, video_path)
  File "K:\sans-ondemand-download-master\download.py", line 39, in download_if_not_exist
    with open(tmp_file_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'FOR500 Windows Forensic Analysis D0208SH5455\\2. Windows Digital Forensics And Advanced Data Triage\\4. Memory and Triage Acquisition\\23. Out of Class Exercise Hard Drive Acquisition with Write Blocker USB  Documents and Cheatsheets.mp4.part'

K:\sans-ondemand-download-master>

I can't figure out how to have it just skip that one and move on.

**Comment by eddiez9** [comment]
As per the readme:

Troubleshooting
Windows path lengths are limited to 260 characters. If you're encountering issues where some videos will download but others won't try the -t flag which will not save the video title.

The path length you have is longer than 260, the following is 271:
K:\sans-ondemand-download-master\FOR500 Windows Forensic Analysis D0208SH5455\2. Windows Digital Forensics And Advanced Data Triage\4. Memory and Triage Acquisition\23. Out of Class Exercise Hard Drive Acquisition with Write Blocker USB Documents and Cheatsheets.mp4.part

Use the -t flag.
