### ISSUE TITLE
the uberequest is not found 

### ISSUE THREAD

**Issue by ahiguero** [eddiez9/sans-ondemand-download#8]
i am not able to get the uberequest.php file as it seems that sans removed it.

**Comment by eddiez9** [comment]
Browse to where you can watch videos, and refresh the page with a filter.

It's there
![image](https://user-images.githubusercontent.com/4555207/70388266-6cc07e00-1a03-11ea-92ce-0660ce85520b.png)

**Comment by ahiguero** [comment]
i am doing those steps but and this is what i get
![image](https://user-images.githubusercontent.com/9029745/70390130-e7e74d00-198d-11ea-838e-d1973551870f.png)

**Comment by eddiez9** [comment]
I can't really help you without seeing what you're seeing.

So you're welcome to do a whole screen recording and share it or give me access to your account to troubleshoot. hello@eddiez.me

**Comment by ahiguero** [comment]
Hello Eddie

this is what i see on my screen

![image](https://user-images.githubusercontent.com/9029745/70623924-c0d68880-1be4-11ea-90c9-5d6f410c0e38.png)

**Comment by eddiez9** [comment]
@ahiguero 

Thanks for sending through the screenshot, that helped me troubleshoot. SANS has published a new version of the same JSON file under a different endpoint it appears. I've updated the script to support both versions.

Check the new instructions and pull the new version of the script. The 8225 file from your screenshot should be the correct one.

Let me know if it works for you.

**Comment by ahiguero** [comment]
this is promising now the error tha ti am getting is that the cookies are expired.

![image](https://user-images.githubusercontent.com/9029745/70808158-b521c800-1d84-11ea-81cf-7700f087c00b.png)

**Comment by eddiez9** [comment]
Looking at the JSON file another guy sent it seems that the Getting Started section doesn't have any cookies so it fails there. I've updated the script again to skip empty sections, could you give it a crack again when you have time. 

You'll have to download the JSON file again cause the cookies do expire pretty quickly.

**Comment by ahiguero** [comment]
we are making progress

it managed to download the first book but it stops with the following error

Traceback (most recent call last):
  File "download.py", line 122, in <module>
    for cookie in reversed(lesson['metadata']['cookies']):
TypeError: argument to reversed() must be a sequence

**Comment by eddiez9** [comment]
Updated script again, can you try again now? it looks like some of the new content is not a video type which is causing that?

**Comment by ahiguero** [comment]
Hello Eddie it worked now buddy excellent work
